FROM python:3.11-alpine

WORKDIR /app

COPY ./requirements.txt /code/requirements.txt

RUN pip install psycopg2-binary
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY . .

CMD ["python", "main.py"]