FROM python:3.11-alpine

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN pip install psycopg2-binary
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY main.py /code/main.py
COPY utils.py /code/utils.py

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]